name: device_calendar_extended_example
description: Demonstrates how to use the device_calendar_extended plugin.
publish_to: 'none'
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.7.4
  device_calendar_extended:
    path: ../
flutter:
  uses-material-design: true
flutter_icons:
  image_path_android: "assets/ic_launcher.png"
  image_path_ios: "assets/Icon-App-1024x1024@1x.png"
  android: true
  ios: true